# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Cyberpunk Neon
include current-theme.conf
# END_KITTY_THEME

enable_audio_bell           no
window_padding_width        10
hide_window_decorations     no
background_opacity          0.9
dynamic_background_opacity  yes
confirm_os_window_close     0
map ctrl+shift+t new_tab !neighbor
cursor_trail 1
map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard