[[track]]
path = "https://youtu.be/foB5El2jxFs?si=05q7w67x64Fx6Lbo"
title = "Deep Productivity"

[[track]]
path = "https://youtu.be/aXYn0u1FeIg?si=LiLcINCYtK0Toj18"
title = "Deep study"

[[track]]
path = "https://youtu.be/_JEYJBG3jhY?si=kntDyE4Ye3x0i-dY"
title = "Distraction Free"

[[track]]
path = "https://youtu.be/Fb8xVz7GXDY?si=VEyZW0H3g7GWxitW"
title = "Ambient Sounds"

[[track]]
path = "https://youtu.be/mFp4gXADeao?si=Lo-irfKY7OFJsyEV"
title = "Work Efficiency"